apiVersion: v1
kind: Service
metadata:
  name: {{ include "anchor-lab.fullname" . }}-alice-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: alice-app
spec:
  selector:
    app: alice-app
  ports:
  - port: 8080
